import Sidebar from './components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full min-h-screen xl:flex relative bg-neutral-50 gap-3">
          <Sidebar />
          <div className={`xl:w-[calc(100%_-_292px)] p-3 transition-all`}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
